format = """
$directory$git_branch$git_status$python$line_break$character"""

[directory]
style = "fg:#8ec07c bold"
format = "[ $path$read_only ]($style)[](fg:#8ec07c) "
truncation_length = 3
truncate_to_repo = true
read_only = " 󰌾"
read_only_style = "fg:#fb4934"

[git_branch]
format = "[ $symbol$branch]($style)"
symbol = " "
style = "fg:#8ec07c"

[git_status]
format = '[$all_status]($style)[](fg:#8ec07c) '
conflicted = "✗"
ahead = ""
behind = ""
diverged = ""
untracked = "✗"
stashed = ""
modified = "✗"
staged = "✗"
renamed = "✗"
deleted = "✗"
style = "fg:#8ec07c"

[python]
format = '([ $virtualenv]($style)[](fg:#d3869b) )'
style = "fg:#d3869b"
detect_extensions = []
detect_files = []
detect_folders = []
pyenv_version_name = false

[character]
success_symbol = "[❯](fg:#b8bb26)"
error_symbol = "[❯](fg:#fb4934)"
