format = """
$directory$git_branch$git_status$python$line_break$character"""

[directory]
style = "fg:#8ec07c bold"
format = "[ $path$read_only ]($style)"
truncation_length = 3
truncate_to_repo = false
read_only = " [ro]"
read_only_style = "fg:#fb4934"

[git_branch]
format = "[·](fg:#665c54)[ $branch ]($style)"
symbol = ""
style = "fg:#fabd2f"

[git_status]
format = '([$all_status ]($style))'
conflicted = "✗"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "✗"
stashed = "~"
modified = "✗"
staged = "✗"
renamed = "✗"
deleted = "✗"
style = "fg:#fabd2f"

[python]
format = '([·](fg:#665c54)[ $virtualenv ]($style))'
style = "fg:#d3869b"
detect_extensions = []
detect_files = []
detect_folders = []
pyenv_version_name = false

[character]
success_symbol = "[❯](fg:#b8bb26)"
error_symbol = "[❯](fg:#fb4934)"
