# ~/.config/kitty/kitty.conf
# Author: MTB

# Font
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        13.0

# Gruvbox Dark Hard
background            #1d2021
foreground            #ebdbb2
selection_background  #d65d0e
selection_foreground  #1d2021
color0  #282828
color8  #928374
color1  #cc241d
color9  #fb4934
color2  #98971a
color10 #b8bb26
color3  #d79921
color11 #fabd2f
color4  #458588
color12 #83a598
color5  #b16286
color13 #d3869b
color6  #689d6a
color14 #8ec07c
color7  #a89984
color15 #ebdbb2

# Window
remember_window_size   yes
initial_window_width   120c
initial_window_height  35c
window_padding_width   4
hide_window_decorations no

# Tabs
tab_bar_edge            bottom
tab_bar_style           powerline
tab_powerline_style     slanted
tab_title_template      {index}: {title}
active_tab_foreground   #1d2021
active_tab_background   #b8bb26
inactive_tab_foreground #a89984
inactive_tab_background #282828

# Splits
enabled_layouts     splits,stack
default_layout      splits

# Focused/unfocused split differentiation
draw_minimal_borders    no
window_border_width     1pt
active_border_color     #98971a
inactive_border_color   #3c3836
inactive_text_alpha     0.8

# Keybindings
map ctrl+shift+h        launch --location=vsplit
map ctrl+shift+b        launch --location=hsplit
map ctrl+equal          change_font_size all +1.0
map ctrl+minus          change_font_size all -1.0
map ctrl+0              change_font_size all 0

# Startup
startup_session startup.conf

# Misc
copy_on_select clipboard
shell /usr/bin/zsh
mouse_map ctrl+left press ungrabbed,grabbed mouse_handle_click link
scrollback_lines 10000
enable_audio_bell no
confirm_os_window_close 0
