# Kitty startup session

new_tab ranger
layout splits
launch ranger

new_tab keybindings
layout splits
launch nvim /home/matt/dotfiles/keybindings.md

new_tab terminal
layout splits
launch zsh
launch --location=vsplit zsh

new_tab dev_01
layout splits
launch zsh
launch --location=vsplit zsh
