# Kitty startup session

new_tab keybindings
layout splits
launch nvim /home/matt/dotfiles/keybindings.md

new_tab yazi
layout splits
launch yazi

new_tab terminal
layout splits
launch zsh
launch --location=vsplit zsh

new_tab dev_01
layout splits
launch zsh

new_tab dev_02
layout splits
launch zsh
