[mgr]
prepend_keymap = [
  { on = ["d"],        run = "yank --cut", desc = "Cut" },
  { on = ["x"],        run = "noop",       desc = "" },
  { on = ["D"],        run = "noop",       desc = "" },
  { on = ["<Backspace>"], run = "remove", desc = "Move to trash" },
]
